spring:
  application:
    name: meeting-rooms
  datasource:
    url: jdbc:h2:mem:meetingrooms;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000
    username: sa
    password: ""
  sql:
    init:
      mode: always
  jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never
